### ISSUE TITLE
Response schemas of actions and functions that return a collection are not accurately described

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#116]
Related to: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/307

### Assemblies affected

`1.0.8`

### Steps to reproduce

Generate the OpenAPI doc. from the CSDL: https://graph.microsoft.com/v1.0/$metadata

### Expected result

Please refer to the linked issue above.

### Actual result

Please refer to the linked issue above.

**Comment by baywet** [comment]
FYI this is impacting Kiota as well (just logged an issue over there)
