### ISSUE TITLE
Suggestion: Re-use existing maintained odata-openapi XSLT

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/OpenAPI.NET.OData#121]
Just found this and wanted to mention there is already a pretty mature conversion utility that could be relatively easily consumed and re-used within a library like this.

It's provided  by OASIS-TCS in the form of an XSL:

[V4-CSDL-to-OpenAPI.xsl](https://github.com/oasis-tcs/odata-openapi/blob/main/tools/V4-CSDL-to-OpenAPI.xsl)

They also provide an XSL for conversion for OData Metadata v2 to OData Metadata v4 which would mean you could generate an OpenAPI doc for ODataV2 APIs.

**Comment by darrelmiller** [comment]
The XSLT provides an alternate way of doing a conversion to OpenAPI.  I'm not aware of any advantages of incorporating that functionality into this library.
