### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by madansr7** [microsoft/OpenAPI.NET.OData#13]
We need an updated readme that describes how this tool can be used. 
It should describe all the available options such as nav prop depth, keys in path, etc.

**Comment by irvinesunday** [comment]
Update README to show in nuget package releases as well: https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/#add-a-readme-to-your-package

**Comment by irvinesunday** [comment]
Related: https://github.com/microsoft/OpenAPI.NET.OData/issues/253

**Comment by irvinesunday** [comment]
> @irvinesunday do you have a better idea of what's expected here? The OOAsUtl tool [does have a fairly complete readme](https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/OoasUtil/README.md). The main readme is doing an ok job at describing the high level object model.
> 
> If we don't have a precise idea of what changes we're expecting, we might want to invest that time to get reference documentation under https://learn.microsoft.com/en-us/openapi/ instead. (of course that requires OpenApi.Net to do it first).
> 
> What do you think?
> 
> (we should probably also include a link to hidi here, since hidi, contrary to ooasutil, is available as a dotnet tool and a docker image)

I agree. The documentation in the README here seems pretty straightforward. I will add a link to Hidi in the OoasUtil README.
