### ISSUE TITLE
Automated releasing to nuget

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#136]
Putting a recap of a few internal conversations here: right now the release to nuget.org is done manually. This is time consuming, error prone and potentially a bottleneck if the main maintainer is out/busy with other priorities.

The main reason why it hasn't been automated yet is due to a lack of time. Hopefully this issue can get things started.

There are already ADO pipeline definitions [here](https://github.com/microsoft/OpenAPI.NET.OData/tree/master/.github/ISSUE_TEMPLATE/workflows) for the nightly publish to myget.
On top of that, there are a couple of additional aspects to consider:
- bumping the version number (or at least validating it's been bumped)
- creating a git tag
- creating a github release base off the tag

Kiota already has some of the later through a standard changelog and a github workflow.

https://github.com/microsoft/kiota/blob/main/CHANGELOG.md
https://github.com/microsoft/kiota/blob/main/.github/workflows/create-release.yml

**Comment by baywet** [comment]
Can you sync with @andrueastman please? I believe dotnet SDK has nightly and scripts to validate the version number as well.

**Comment by danielmbaluka** [comment]
Yes, I will engage @andrueastman to see how they do it. Thanks.
