### ISSUE TITLE
URL templates missing quotes around enum types

### ISSUE THREAD

**Issue by zengin** [microsoft/OpenAPI.NET.OData#140]
According to the spec, it seems that we need quotes around the enum type name but not the namespace:
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_PrimitiveLiterals
> `ColorEnumValue eq Sales.Pattern'Yellow',`
> `ColorEnumValue eq 'Yellow',`

These quotes are missing in the translated OpenAPI doc.

see https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1156 for more details.

**Comment by baywet** [comment]
Thanks for reporting the issue. Although the example you provided mentions enum, the original issue is with functions parameters. I've just authored #143 to address this issue.
