### ISSUE TITLE
Support complex type with navigation property

### ISSUE THREAD

**Issue by xuzhg** [microsoft/OpenAPI.NET.OData#15]
Do we support the navigation property in complex type?

For example:

```
Entity Type (AddressInfo)
  |- ID (Edm.Int32)

Complex Type (Address)
    |- City (Edm.String)
    |- Street (Edm.String)
    |- AddressInfo (AddressInfo)

Entity Type (Customer)
   -> ID (Edm.Int32)
   -> Location (Address)
   -> Locations (Collection(Address))

EntitySet (Customers -> Customer)
```
So, the path:

`~/Customers/{ID}/Location/AddressInfo ` should be valid.
`~/Customers/{ID}/Locations/AddressInfo` should be invalid.

**Comment by darrelmiller** [comment]
Now that this is supported in Microsoft Graph AGS, we should add this capability.  I expect teams to start using it soon.

**Comment by baywet** [comment]
Note: in the provided example `~/Customers/{id}/Location` should also be valid, but the conversion lib should already handle it today, we should double check though while we're at it.

**Comment by baywet** [comment]
update, after some testing, it appears that the current conversion process also doesn't produce anything for `~/Customers/{id}/Location` when it should. For example TripService doesn't have any path item for `Airports/{id}/Location`.

Additionally, this behavior should be driven by the existing `EnableNavigationPropertyPath` conversion setting.

**Comment by baywet** [comment]
After internal discussions with @mikepizzo here are some additional precisions for the operations:

~/Customers/{id}/Location:
 - GET
 - PATCH
 - DELETE (if the property is nullable)

~/Customers/{ID}/Location/AddressInfo
- GET
- PATCH
- DELETE (if the property is nullable)

(NavigationPropertyRestrictions apply)

~/Customers/{ID}/Location/AddressInfos (assuming we have a collection instead)
- GET (list)
- POST (inserting)

(NavigationPropertyRestrictions apply)

~/Customers/{ID}/Location/AddressInfos/{id} (assuming we have a collection instead)
- GET
- PATCH
- DELETE

(NavigationPropertyRestrictions apply)

Awaiting additional information on the behavior of ContainsTarget ($ref etc...)

**Comment by baywet** [comment]
ContainsTarget semantically behaves the same way as a navigation property on an entity type, additionally

~/Customers/{id}/Locations: (assuming they are a collection of complex types)
- GET (lists the collection)
- POST (replace the whole collection)
