### ISSUE TITLE
[Feature] Uses Referenceable annotation to control generation of $ref paths

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#151]
We want to introduce a `Referenceable` `Org.OData.Capabilities.V1.NavigationRestrictions` annotation for controlling the generation of `$ref` paths. This shall be used instead of relying on `ContainsTarget=false` or the absence of this attribute in a navigation property as a condition for generating `$ref` paths.

**Comment by baywet** [comment]
related #123
