### ISSUE TITLE
[Feature] Support for a range of response status codes

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET.OData#153]
Consider adding support for a range of response status codes as described in [OAS 3](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#patterned-fields-1):
> Any HTTP status code can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. A Reference Object can link to a response that is defined in the OpenAPI Object's components/responses section. This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML. To define a range of response codes, this field MAY contain the uppercase wildcard character X. For example, 2XX represents all response codes between [200-299]. Only the following range definitions are allowed: 1XX, 2XX, 3XX, 4XX, and 5XX. If a response is defined using an explicit code, the explicit code definition takes precedence over the range definition for that code.

e.g., 2XX.

This should ideally be an opt-in feature that should be set via `OpenApiConvertSettings`.

**Comment by darrelmiller** [comment]
Response should look something like below. Error payload should be the same as it currently is.

```yaml
openapi: 3.0.1
info:
  title: Wildcard status codes
  version: 1.0.0
paths:
  /:
    get:
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema: 
                type: object
        4XX:
          description: error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/error"
        5XX:
          description: error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/error"

components:
  schemas:
    error: {}
            

```

**Comment by irvinesunday** [comment]
@peombwa I believe this issue was fixed with this PR: https://github.com/microsoft/OpenAPI.NET.OData/pull/167

**Comment by peombwa** [comment]
@irvinesunday, this issue relates to success (2xx) status code ranges. We've had challenges with certain APIs returning success status codes that are not defined in the OpenAPI files. e.g., https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907#issuecomment-947183924.

The fix that was made in [adds the ability to define error responses on error codes instead of default by baywet · Pull Request #167 · microsoft/OpenAPI.NET.OData (github.com)](https://github.com/microsoft/OpenAPI.NET.OData/pull/167) was for error responses and not success responses.
