### ISSUE TITLE
OpenAPI document has no endpoint descriptions

### ISSUE THREAD

**Issue by calebkiage** [microsoft/OpenAPI.NET.OData#154]
The OpenAPI document generated from the microsoft graph API has descriptions for HTTP actions (e.g. GET, POST) but no descriptions for the actual endpoints. The specific use case where these descriptions would be useful is when generating a CLI from the OpenAPI file using kiota. The help docs for CLI commands would come from the descriptions.

Example:
Given an endpoint /users/messages with an action GET, the CLI would have the command structure `[cli] users messages list`. Users could then get help descriptions when they call `[cli] users messages list -h` but not `[cli] users -h` or `[cli] users messages -h`.

**Comment by baywet** [comment]
To be specific we're referring to the description property at the path item level

**Comment by baywet** [comment]
Thanks for reporting this @calebkiage, I've just authored #156 which addresses this issue.
Kiota builder already reads into the information from the description so when this PR gets merged, published and the descriptions updated, this information will flow naturally all the way to the code dom class (request builder).
Right now I can see that the [build commands for aggregation](https://github.com/microsoftgraph/msgraph-cli/blob/daed1b1fd36771cb27e9f19dabd0840a7ec9df85/src/generated/Applications/ApplicationsRequestBuilder.cs#L78) don't have the [description from the request builder](https://github.com/microsoftgraph/msgraph-cli/blob/daed1b1fd36771cb27e9f19dabd0840a7ec9df85/src/generated/Applications/ApplicationsRequestBuilder.cs#L19), you might want to update your refiner to copy that information from the class when these methods are added to the DOM. (and maybe your code writer to leverage it and add it to the command).
