### ISSUE TITLE
Navigation property paths generation and restrictions.

### ISSUE THREAD

**Issue by sherlock1982** [microsoft/OpenAPI.NET.OData#179]
I have an entity set of `Queues` with a collection of `Members`. Please could you clarify the following cases.

### Current behavior:
`ConvertToOpenApi` function reports `GET` method on the path `/Queues(Id)/Members` even though it is not defined in Queues controller. I  can globally turn it off with an option `EnableNavigationPropertyPath=false`.

### Expected result:
Create the path only if it really exists?

The other issue affects security.

### Current behavior:
`Queues` access is restricted to a specific scheme and role and indeed I see it correctly in resulted OpenAPI document.
But `/Queues(Id)/Members` is not reported to be restricted and therefore no access token will be requested and I will get 401.

### Expected result:
Could read restriction somehow be applied to `/Queues(Id)/Members` ? I mean well it should be the same as `Queue` but not it's not reported. `Member` is an entity type but not a part of an entity set. It looks like only `EntitySet` can have read restrictions.

**Comment by darrelmiller** [comment]
The conversion library generates what should be implemented based on the CSDL and capability annotations that are present.  Could you share your CSDL to help us understand the output you are getting?  If your Queue entity has a members collection then by definition, OData assumes that path exists unless you tell it that it doesn't.

**Comment by sherlock1982** [comment]
I think we can close it - i understood everything now.

1. The whole OData converter generates endpoints based on OData metadata and it doesn't have information on if endpoint is really defined.  `EnableNavigationPropertyPath` is true by default and automatic. Therefore one needs to properly define the navigational endpoint for this to work. Also `EnableNestedPaths` is not implemented for version 8.X

2. OData restrictions are informational only anyway. Authorization library is in beta stage for 2 years and not implemented for current library. Authorization is purely handled by ASP.Net Core controllers, filters, policies e.t.c. So there's no point to define any permissions in OData metadata file.
I simply defined global requirement to be authorized.

**Comment by xuzhg** [comment]
> I think we can close it - i understood everything now.
> 
> 1. The whole OData converter generates endpoints based on OData metadata and it doesn't have information on if endpoint is really defined.  `EnableNavigationPropertyPath` is true by default and automatic. Therefore one needs to properly define the navigational endpoint for this to work. Also `EnableNestedPaths` is not implemented for version 8.X so we need to do everthing manually.

Actually, you can change the "default" behaviour using the path provider. See information here: https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataRoutingSample/OpenApi

**Comment by sherlock1982** [comment]
You are right but this example is weird and needs modifications. 
It generates all possible endpoints and makes invalid OpenAPI spec anyway due to duplicated operationIds.

Though in general this is the way to go and at some point I will switch there.

I understand that both `Item/:key` and `Item(key)` are available but I don't want them all in OpenAPI spec. 
The same for operations.

**Comment by xuzhg** [comment]
@[sherlock1982](https://github.com/sherlock1982) Both OpenAPI OData converter setting and ASP.NET Core OData routing configuration has the setting to suppress the key as segment ( Item/{key} ) or key in parentheses (Item({key})
