### ISSUE TITLE
Add support for @odata.context and @odata.count

### ISSUE THREAD

**Issue by sherlock1982** [microsoft/OpenAPI.NET.OData#196]
We have paging support and can specify `$count=true` to get the count of all elements. 
Unfortunately there's no way to get `@odata.count` value from a response.

Without this OData paging features are kind of unusable.
In order to add it I modified the document approximately like this:

            foreach (var path in document.Paths.Values)
            {
                foreach (var operation in path.Operations.Values)
                {
                    if (operation.OperationId.Contains(".List", StringComparison.Ordinal))
                    {
                        var props = operation.Responses["200"].Content["application/json"].Schema.Properties;
                        props.Add("@odata.context", new OpenApiSchema()
                        {
                            Type = "string"
                        });
                        props.Add("@odata.count", new OpenApiSchema()
                        {
                            Type = "integer",
                            Format = "int32"
                        });
                    }
               }
           }

**Comment by darrelmiller** [comment]
@sherlock1982 Do you have a need for @odata.context? I understand how count and nextlink are useful but to date the only tooling that I have seen that uses @odata.context is native OData tooling and therefore does not seem useful in an OpenAPI description.

**Comment by sherlock1982** [comment]
It's ok without `@odata.context`. 
Thought to add it just because it exists :-)

**Comment by irvinesunday** [comment]
We already have a setting `context.Settings.EnablePagination` that enables `@odata.nextLink` in collection responses. We can append `@odata.count` to this as well.
