### ISSUE TITLE
The default value of $Top should not be fixed = 50 

### ISSUE THREAD

**Issue by Behnam-Emamian** [Microsoft/OpenAPI.NET.OData#20]
I think we need to pass the default $Top value to CreateTop method.

**Comment by xuzhg** [comment]
@Behnam-Emamian Thanks for your input. I think we can use the covert setting to config the $top, $skip default value. Any contribution is welcome.

**Comment by Behnam-Emamian** [comment]
I am thinking something like OpenApiConvertSettings for Serialize method, is it good?

**Comment by xuzhg** [comment]
Would you please give more detail design then we can discuss it?

**Comment by Behnam-Emamian** [comment]
OpenApiConvertSettings.cs

a new class exactly like OpenApiConvertSettings for passing the settings to Serialize methods

**Comment by xuzhg** [comment]
Thanks for your input and contribution.
