### ISSUE TITLE
Missing add action of "followed sites" in the OpenAPI document

### ISSUE THREAD

**Issue by maisarissi** [microsoft/OpenAPI.NET.OData#201]
The [add action of followed site](https://docs.microsoft.com/en-us/graph/api/site-follow?view=graph-rest-1.0&tabs=http) is missing in the OpenAPI description - /users/{user-id}/followedSites/add is missing.
![image](https://user-images.githubusercontent.com/22648831/159052083-edb4357e-dc88-49cf-ac55-5ed6ee83a194.png)

And According to the metadata, it should be supported:

      <Action Name="add" IsBound="true">
        <Parameter Name="bindingParameter" Type="Collection(graph.site)" />
        <Parameter Name="value" Type="Collection(graph.site)" />
        <ReturnType Type="Collection(graph.site)" />
      </Action

This is still missing in the 1.0.10 version.

We would expect to have all supported paths in the OpenAPI document so we could generate PowerShell cmdlets for each of them.

**Comment by baywet** [comment]
it seems the conversion process is ignoring actions that are bound to collections when those are navigation properties but converting them on entity sets
