### ISSUE TITLE
Provide a way to get the assembly version that was used when generating a file

### ISSUE THREAD

**Issue by calebkiage** [microsoft/OpenAPI.NET.OData#208]
It would be useful to provide an easy way to get the assembly version of the library that was used in generating an OpenAPI file e.g. in a comment in the generated file. This is useful for bug reporting and traceability.

**Comment by darrelmiller** [comment]
This should be an extension in the info object.  How about?

```yaml
openapi: 3.0.3
info:
  title: Generated OpenAPI from CSDL
  version: 1.0.0
  x-generatedBy:
    toolName: OpenApi.Net.CSDL
    toolVersion: 1.0.11
```
