### ISSUE TITLE
OData actions are applied to derived types

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET.OData#221]
OData actions bound to base types are being applied to derived types resolved via OData casting. From my testing, calling an action from an OData cast-derived type is not supported by the service e.g.,
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7061532/169399735-42b179da-9058-41ab-81d8-702c1a454959.png)

This seems to occur even with `ExpandDerivedTypesNavigationProperties = false`.

Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1000.

### Assemblies affected
1.0.10

**Comment by darrelmiller** [comment]
@irvinesunday Is there a setting to disable generating actions on derived types that is independent to the `ExpandDerivedTypesNavigationProperties`?

**Comment by irvinesunday** [comment]
> @irvinesunday Is there a setting to disable generating actions on derived types that is independent to the `ExpandDerivedTypesNavigationProperties`?

@darrelmiller, no we don't have such a setting. 
Despite not being applicable in the Graph service, are actions on derived types allowable in OData?

**Comment by maisarissi** [comment]
Hey folks. This is blocking us from releasing PowerShell SDK, and I saw that this issue was added into the 1.0.11 milestone, instead of being prioritized as part of 1.0.10. Is that right?
Please, can you prioritize this? @CarolKigoonya @irvinesunday @darrelmiller

**Comment by irvinesunday** [comment]
> Hey folks. This is blocking us from releasing PowerShell SDK, and I saw that this issue was added into the 1.0.11 milestone, instead of being prioritized as part of 1.0.10 release. Is that right? Please, can you reevaluate this? @CarolKigoonya @irvinesunday @darrelmiller

The fix will go out in 1.0.11-preview1. I've labelled it as a p1

**Comment by maisarissi** [comment]
When is the release date for 1.0.11? Per my understanding, we are getting close to release the 1.0.10 version and update DevX API to use it, but until we get this fixed, the PowerShell SDK can't be generated.
We have added this item as part of our 1.0.10 tracking working on PS side: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1265

**Comment by irvinesunday** [comment]
@maisarissi `v1.0.10` was released and DevX API is currently on this version. `v1.0.11-preview1` is the next candidate and is scheduled to go out with the end of milestone 1.0.11; however, I am fast-tracking this so that we can release it by next week.

**Comment by maisarissi** [comment]
Thanks for the additional details @irvinesunday
