### ISSUE TITLE
Add the documentation links from `Links` annotations in CSDL to OpenAPI Operations 

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#230]
Given the `Links` annotation in the CSDL:
![image](https://user-images.githubusercontent.com/40403681/172565339-06cecacd-d63c-4751-bb35-dcc8aa633fd1.png)

We would want to add the external doc. link (from the **href** property) to the generated OpenAPI doc. in the `ExternalDocs` property of operations:
![image](https://user-images.githubusercontent.com/40403681/172566890-38a3f55b-61e3-420a-9184-733fc36760d7.png)

**Comment by baywet** [comment]
just a quick note on the openapi example, it contains a MD extension that shouldn't be here.

**Comment by irvinesunday** [comment]
> just a quick note on the openapi example, it contains a MD extension that shouldn't be here.

FYI @millicentachieng to action on API Doctor
