### ISSUE TITLE
Bound operations not appended to non-contained navigation property paths

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#232]
Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/201

With this bound operation:
![image](https://user-images.githubusercontent.com/40403681/173085653-2b8c916d-1632-40c6-8480-062fc47a013d.png)

and given this non-contained navigation property:
![image](https://user-images.githubusercontent.com/40403681/173085516-e8a7bb8b-23f4-433f-96d7-d7e2c11128b0.png)

and given a schema namespace value of `microsoft.graph`

We expect to generate paths similar to below:
`.../followedSites/microsoft.graph.add`

This is not the case with the current version because we check the containment of the navigation property [here](https://github.com/microsoft/OpenAPI.NET.OData/blob/079f8ea2dfa227325a2ff7905cab86f15ee2347f/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L682-L685).
According to the spec. doc., see [ref](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793738):

```
Actions and Functions MAY be bound to an entity type, primitive type, complex type, or a collection...
The namespace- or alias-qualified name of a bound operation may be appended to any URL that identifies 
a resource whose type matches, or is derived from, the type of the binding parameter. 
```
This may be applied to any navigation property segment as long as its type matches the type of the binding parameter.

**Comment by baywet** [comment]
Thanks for documenting this in details. I'm torn here.
Historically we've decided to only bind operations to contained navigation properties, entity sets or singletons. Or in other words to only have operations on the entities canonical path. This is to avoid expanding too many paths and growing the description too much. It makes sense since why would one call an operation on a "deeper path" when a shallower one is already available?

This case is an interesting example, and poor API design IMHO. The followed sites should instead be a collection of "followedSite", contained. FollowedSite is a new entity type that semantically belongs to the user (is contained), has a non-contained reference to site (existing entity), and potentially other properties like "followedDate", "followedReason", etc...

But since the API is not getting fixed any time soon, we probably out to make an opiniated decision here.
What would be the consequence of setting contains target true for that property?
Can we rely on an annotation/attribute that would signal "bind operations even though this is not contained"? 
Do we have other cases like this one?

**Comment by baywet** [comment]
after a quick chat with @darrelmiller it looks like there's no such annotation. Can you have a look at the implications of changing contains target for that property? and see if we have other instances of that scenario?

**Comment by irvinesunday** [comment]
> after a quick chat with @darrelmiller it looks like there's no such annotation. Can you have a look at the implications of changing contains target for that property? and see if we have other instances of that scenario?

Appending `ContainsTarget=true` generates 1042 more paths. I'm collating the list of other navigation props. that have a similar issue.

**Comment by irvinesunday** [comment]
The number of similar scenarios are quite significant. Below are just a couple of them:

**Navigation properties:**
- filesFolder
- createdOnBehalfOf
- owners
- directReports
- manager
- memberOf
- transitiveMemberOf
- registeredOwners
- members
- driveItem
- group
- teachers
- schools
- user
- acceptedSenders
- calendar
- membersWithLicenseErrors
- parentNotebook
- parentSection
- baseTypes
- sites
- channel

**Entities:**
- directoryObject
  - directReports/{directoryObject-id}
  -  memberOf/{directoryObject-id}
  -  transitiveMemberOf/{directoryObject-id}
- driveItem
- contentType
- site 
 

Clearly, setting their containment to `true` will be unfeasible, as the number of paths generated will just be humongous.

**Comment by irvinesunday** [comment]
From discussions with @darrelmiller, the recommendation was to come up with a custom annotation that will be appended to a given operation. This annotation will list the non-contained navigation properties that should append paths to the given operation. The annotation would look something like:

![image](https://user-images.githubusercontent.com/40403681/187180598-a02b12d6-ea68-4dba-b16c-bb37e8e7e537.png)

**Comment by irvinesunday** [comment]
This was the proposal from Mike for the annotations to be used.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/40403681/198292606-a33d23f3-7a13-42b4-be1c-7c7fda1ba064.png)

**Comment by irvinesunday** [comment]
After further discussions, the below annotation structure has been arrived at:

```
<Term Name="RequiresExplicitBinding" Type="Core.Tag" DefaultValue="true" AppliesTo="Action, Function">
  <Annotation Name="Description" Edm.String="This bound action or function is only available on model elements annotated with the ExplicitOperationBinding term."/>
</Term>

<Term Name="ExplicitOperationBindings" Type="Collection(Edm.String)"> 
   <Annotation Name="Description" Edm.String="The qualified names of explicitly bound operations that are supported on the target model element. These bindings are in addition to any bindings to the type of the target model element not annotated with RequiresExplicitBinding"/> 
</Term>
```

Example usage:

```
<Action Name="forward" IsBound="true" >
  <AnnotationTerm="Org.OData.Capabilities.V1.RequiresExplicitBinding"/>
  <ParameterName="bindingParameter" Type="self.email"/>
  <ParameterName="recipient" Type="Collection(self.recipent)"/>
  <ReturnTypeType="self.email" />
</Action>

<Annotations Target="self.Container/me/email">
  <Annotation Term="Org.OData.Capabilities.V1.ExplicitOperationBindings">
    <Collection>
      <String>self.forward</String>
    </Collection>
  </Annotation>
</Annotations>
```

Find further reading of the proposal [here](https://issues.oasis-open.org/browse/ODATA-1538#)

**Comment by irvinesunday** [comment]
This issue is blocked while waiting for the resolution of: https://github.com/OData/odata.net/issues/2543

**Comment by darrelmiller** [comment]
Can we confirm that we are no longer blocked?

**Comment by irvinesunday** [comment]
> Can we confirm that we are no longer blocked?

This is now unblocked. The PR to resolve this: https://github.com/microsoft/OpenAPI.NET.OData/pull/378

**Comment by irvinesunday** [comment]
Resolved by: https://github.com/microsoft/OpenAPI.NET.OData/pull/378
