### ISSUE TITLE
information / documentation

### ISSUE THREAD

**Issue by figuerres** [microsoft/OpenAPI.NET.OData#253]
i am currently using nswag for my open api front end.
can i use this package to plug into nswag ?
if i can how should i do that ?

if not can we see an example of an open api demo that uses this package to expose odata ?

right now i see several parts of how to get OData and Open API working but it seems like there are 10 different ways that folks are doing it and getting different amounts of success in the end.

**Comment by darrelmiller** [comment]
This library generates OpenAPI v3 descriptions.  If nswag can take those as input then it should work just fine with nswag.

**Comment by irvinesunday** [comment]
@figuerres like @darrelmiller mentioned, this package takes in an Edm Model (from CSDL) and converts it to CSDL:

```CSharp
CsdlReader.TryParse(XElement.Parse(csdlText).CreateReader(), out model, out errors)
OpenApiConvertSettings settings = new OpenApiConvertSettings();
OpenApiDocument document = model.ConvertToOpenApi(settings);
```
Does this fit in with your requirements?

**Comment by irvinesunday** [comment]
@figuerres closing this issue. Feel free to re-open if you feel the need to
