### ISSUE TITLE
Schemas should declare properties that cannot participate in a request as `ReadOnly`

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET.OData#254]
We currently generate OpenAPI documents with the same schema object in both the request and response bodies of operations for a given path object as such:
``` yml
paths:
  post:
    tags:
      - users.user
    summary: Create user
    operationId: users.user_CreateUser
    requestBody:
      description: New entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/microsoft.graph.user'
      required: true
    responses:
      '201':
        description: Created entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.user'
      default:
        $ref: '#/components/responses/error'
    x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.user:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.directoryObject'
        - title: user
          type: object
          properties:
            aboutMe:
              type: string
              description: A freeform text entry field for the user to describe themselves. Returned only on $select.
              nullable: true
            createdDateTime:
              type: string
              description: 'The date and time the user was created. Read-only.'
              format: date-time
              nullable: true
            messages:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.message'
              description: The messages in a mailbox or folder. Read-only. Nullable.
            manager:
              $ref: '#/components/schemas/microsoft.graph.directoryObject'
```
While this works, we should also mark all properties that cannot be sent as part of a request as `readonly` to accurately represent operations.

### Proposal
Let's declare properties in the schema object that cannot be sent as part of a request as `readonly`. We can use the following rules to determine if a property should be marked as `readonly`:
- Navigation Properties:
  - [ ] Containment navigation properties. The navigation properties are set via `additionalData` property bag in all SDKs (`@Odata.Bind`).
  - [ ] Non-containment navigation properties assuming deep inserts/updates are not supported by a service. We should check to see if the EntityContainer, EntitySet, or Collection has [DeepInsertSupport](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#deepinsertsupporttype) and [DeepUpdateSupport](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#deepupdatesupporttype) annotations set to false. 
- Properties:
  - [x] Properties with `Computed` annotation in the CSDL.

``` diff
paths:
  post:
    tags:
      - users.user
    summary: Create user
    operationId: users.user_CreateUser
    requestBody:
      description: New entity
      content:
        application/json:
          schema:
            $ref: '#/components/requestBodies/microsoft.graph.user'
      required: true
    responses:
      '201':
        description: Created entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.user'
      default:
        $ref: '#/components/responses/error'
    x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.user:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.directoryObject'
        - title: user
          type: object
          properties:
            aboutMe:
              type: string
              description: A freeform text entry field for the user to describe themselves. Returned only on $select.
              nullable: true
            createdDateTime:
              type: string
              description: 'The date and time the user was created. Read-only.'
              format: date-time
              nullable: true
+             readOnly: true
            messages:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.message'
              description: The messages in a mailbox or folder. Read-only. Nullable.
+             readOnly: true
            manager: # Property is set via additionalData property bag in all SDKs via @Odata.Bind.
              $ref: '#/components/schemas/microsoft.graph.directoryObject'
+             readOnly: true
```

### Considerations
- The OData client does not currently support deep insert/update - [OData/odata.net/issues/736](https://github.com/OData/odata.net/issues/736#issuecomment-1168458820). Can we safely assume that deep insert/update is not supported by the service? If so, then the CSDL should be annotated as not supporting deep inserts/updates via  [DeepInsertSupport](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#deepinsertsupporttype) and [DeepUpdateSupport](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#deepupdatesupporttype) annotations.
- Can deep insert/update be performed on containment navigation property?

**Comment by millicentachieng** [comment]
@peombwa
I don't understand why we would need to declare containment navigation properties as read-only. Could you share more context on this.

@darrelmiller, @baywet. Is it safe to declare all non-containment navigation properties as read-only given that the OData client does not currently support deep insert/update?

**Comment by darrelmiller** [comment]
@peombwa I think you have your contained/non-contained scenarios backwards.  But in reality, containment shouldn't affect our decision here.

- Computed should definitely generate the readonly attributed for OpenAPi 3.0 specs.  
- I think we can consider all navigation properties as read only unless DeepInsert/DeepUpdate is supported.  But maybe it is better to add a x-navigationProperty: true rather than setting ReadOnly.  Thoughts?

**Comment by millicentachieng** [comment]
Adding `x-navigationProperty: true` seems like the better option here.  Once we agree on this I'll create a new ticket to track this.

**Comment by irvinesunday** [comment]
> @peombwa I think you have your contained/non-contained scenarios backwards. But in reality, containment shouldn't affect our decision here.
> 
> * Computed should definitely generate the read-only attributed for OpenAPi 3.0 specs.
> * I think we can consider all navigation properties as read-only unless DeepInsert/DeepUpdate is supported.  But maybe it is better to add a x-navigationProperty: true rather than setting ReadOnly.  Thoughts?

I believe the syntax should be `x-ms-navigationProperty`
Also, would we want to identify other other types of properties and have the extension as `x-ms-propertyType`?

**Comment by baywet** [comment]
I don't have an opinion on the matter.

**Comment by peombwa** [comment]
Sorry for the delayed response to this (My Github notification has been out of sync).

Yes, `x-ms-navigationProperty` will work for our scenario. We will have pre-generation step that marks the properties as readOnly so AutoREST can exclude them from the request body parameters.
