### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type 'Microsoft.OData.Edm.EdmPrimitiveTypeReference' to type 'Microsoft.OData.Edm.IEdmStringTypeReference'.'

### ISSUE THREAD

**Issue by imabusyman** [microsoft/OpenAPI.NET.OData#26]
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.OData.Edm.EdmPrimitiveTypeReference' to type 'Microsoft.OData.Edm.IEdmStringTypeReference'.
  Source=Microsoft.OpenApi.OData.Reader
  StackTrace:
   at Microsoft.OpenApi.OData.Generator.OpenApiEdmTypeSchemaGenerator.CreateSchema(ODataContext context, IEdmPrimitiveTypeReference primitiveType)

**Comment by xuzhg** [comment]
do you have the repro?
