### ISSUE TITLE
Action responses not serialized

### ISSUE THREAD

**Issue by mispeer** [microsoft/OpenAPI.NET.OData#29]
Action responses are always serialized in the generated document as 204 No Content. 

### Steps to reproduce

Serialize any OData metadata where an action has a response type. e.g.
<Action Name="AddRecurrence" IsBound="true">
<Parameter Name="entity" Type="mscrm.appointment" Nullable="false" />
<Parameter Name="Target" Type="mscrm.recurringappointmentmaster" Nullable="false" />
<ReturnType Type="mscrm.recurringappointmentmaster" Nullable="false" />
</Action>

### Expected result

In this example, the response should be 200 and the returnType defined in the openAPI document.

### Actual result

204 is always generated for Actions.

### Additional detail

This appears to be due to OpenApiResponseGenerator.cs line 97 filtering all Actions to have 204, even though they may contain a response. 
It would seem per the OASIS Mapping documentation 4.5.3 :
HTTP response code 204 if the response has no body 
The correct approach is to return 204 for isAction && returnType == null.

**Comment by xuzhg** [comment]
Fixed at https://github.com/microsoft/OpenAPI.NET.OData/commit/db3c3e886c638c9851c00d532865b09f226889fd. Thanks
