### ISSUE TITLE
required is missing on path parameters

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#297]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

1.2.0-preview4

### Steps to reproduce

```shell
dotnet tool install -g Microsoft.OpenAPI.Kiota --prerelease
kiota show -k msgraph::microsoft-graph
```

### Expected result

No errors about path parameters missing the required property.

### Actual result

```
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}/parameters/1/in]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}~1createdOnBehalfOf/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}~1createdOnBehalfOf/parameters/1/in]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}~1extensionProperties/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}~1extensionProperties/parameters/1/in]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}~1extensionProperties~1{extensionProperty-id}/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}~1extensionProperties~1{extensionProperty-id}/parameters/1/in]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}~1extensionProperties~1$count/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}~1extensionProperties~1$count/parameters/1/in]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: "required" must be true when parameter location is "path" [#/paths/~1applications~1{application-id}~1federatedIdentityCredentials/parameters/1/required]
fail: Kiota.Builder.KiotaBuilder[0]
      OpenApi Parsing error: Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1applications~1{application-id}~1federatedIdentityCredentials/parameters/1/in]
```

(logs truncated for brevity)

### Additional detail

This is using the latest open API description for Microsoft Graph which has been using the current version of this library to be generated by the weekly process.

**Comment by peombwa** [comment]
This is also affecting PowerShell module - https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1577#pullrequestreview-1148361669.

How is the alternate key (`appId`) supposed to be used in the context of OAS 3? There is no direct equivalent of [OData's AlternateKeys](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_AlternateKeys) term in OAS 3 that I can think of. Aliasing of parameters is still an open feature request for OAS - https://github.com/OAI/OpenAPI-Specification/issues/2298.

**Comment by irvinesunday** [comment]
This is also potentially affecting Go and PowerShell snippets in GE: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2174

**Comment by millicentachieng** [comment]
> This is also affecting PowerShell module - [microsoftgraph/msgraph-sdk-powershell#1577 (review)](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1577#pullrequestreview-1148361669).
> 
> How is the alternate key (`appId`) supposed to be used in the context of OAS 3? There is no direct equivalent of [OData's AlternateKeys](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_AlternateKeys) term in OAS 3 that I can think of. Aliasing of parameters is still an open feature request for OAS - [OAI/OpenAPI-Specification#2298](https://github.com/OAI/OpenAPI-Specification/issues/2298).

@peombwa The idea is to generate paths that utilize alternate parameters e.g. for the alternate key `appId`, the path will be `/applications(appId={appId})`.

I'm closing this issue since removing support for alternate keys fixed this issue. Let's have further discussions [here](https://github.com/microsoft/OpenAPI.NET.OData/issues/120).
