### ISSUE TITLE
Default presence of `odata.type` property in generated OpenAPI

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#304]
Currently, all models are generated by with a default value for the `@odata.type` property which is further propagated into generated models in Kiota. This shouldn't be an issue per se but various workloads seem to not support the existence of this property as seen in the numerous linked issues to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534#issue-899279074.

The proposal therefore is to have the `@odata.type` not set by default in the result openApi generation and have it set in the following conditions where type disambiguation is necessary as the API will need to know the type to infer and take advantage of the properties.

1. The type derives from an abstract type
2. One of its base/parent types is referenced as the type for a property in another type (except if the base is entity).
3. One of its base types is referenced as the type in an odata action in another type (except if the base is entity).

Possibly, the default behaviour could have the `@odata.type` property set/unset and then we would add a setting to enable this behaiour as this may not really be a valid ask for another odata API needing the conversion to be performed.

Related issues
- https://github.com/microsoftgraph/msgraph-sdk-php/issues/1006
- https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/495

**Comment by irvinesunday** [comment]
@peombwa / @timayabi2020 is this a behaviour that we need enabled/disabled for PowerShell as well?

**Comment by peombwa** [comment]
@irvinesunday, it looks like we don't expose `@odata.type` property on models though DevX API - https://graphexplorerapi.azurewebsites.net/openapi?operationIds=drives.drive.root.createUploadSession&title=Files&openapiversion=3&style=Powershell&graphVersion=v1.0,
