### ISSUE TITLE
Augmenting OpenApi Output With Xml Comments

### ISSUE THREAD

**Issue by Olamshin** [microsoft/OpenAPI.NET.OData#31]
Hi! I like the progress in this project so far! I would like to know if there is any way I can augment the output OpenApi document with C# xml comments generated in Visual Studio. I have browsed through the repo and couldnt determine a viable entry point to add such configuration. I have checked out the other OpenAPI.Net project: [CSharpAnnotations](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations), but it is not aware of OData models it seems. I basically need a union of both projects.

I have code that can parse the xml comments but i dont have a valid identifier to match the Controller Action in the xml with the Path in the OpenAPI document. Please let me know if there are other avenues to inject custom commentary besides xml comments. I am open to submitting a PR if a suitable design is approved.

Thanks!

**Comment by jakobthordar** [comment]
Has there been an update to this? I am currently generating and openapi document using this project and then importing it into Postman. It would be great if it was in any way possible to add documentation to the openapi document generatwd using this project.

Reading xml documentation would be great but if there is any other way I would appreciate if anyone could point me in the right direction. :)

**Comment by darrelmiller** [comment]
Documentation annotations in CSDL are now used to fill the Summary and Description properties for schemas, operations and paths.
