### ISSUE TITLE
Wrong response status code for Drive upload endpoint

### ISSUE THREAD

**Issue by Ndiritu** [microsoft/OpenAPI.NET.OData#310]
The Graph OpenAPI description for `PUT`  `/drives/{drive-id}/items/{driveItem-id}/content` defines a `204` yet the API returns a `201` with either the new/updated drive item resource.

[Docs reference](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)

**Comment by peombwa** [comment]
This issue also affects `PUT https://graph.microsoft.com/v1.0/me/photo/$value`. Its response code is defined as `204` yet the API returns `200`. See [API reference](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#example-1-update-the-photo-of-the-user).

To resolve the issue, we should ensure that all success status codes in the OpenAPI document are declared as `2XX` when `UseHTTPStatusCodeClass2XX` is set to `true`.
