### ISSUE TITLE
Missing query parameters for raw count endpoints

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#313]
The raw count endpoints ($count path item) are missing query parameters descriptions from the parent endpoint.

The service supports `https://graph.microsoft.com/v1.0/me/messages/$count?$filter=isDraft eq false` but the conversion process is missing the query parameters from messages on the $count path item.

### Assemblies affected

1.2.0-preview8

### Expected result

$count endpoints to have query parameters from the parent set/collection (filter, search and custom parameters)
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection

**Comment by calebkiage** [comment]
@baywet, the headers are also missing

**Comment by irvinesunday** [comment]
> @baywet, the headers e.g. `Consistency-Level` are also missing

@calebkiage this support was added in this PR: https://github.com/microsoft/OpenAPI.NET.OData/pull/305
