### ISSUE TITLE
The OpenAPI version field is not limited to dotnet version specs

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#346]
The dotnet [version type](https://learn.microsoft.com/en-us/dotnet/api/system.version?view=net-7.0) is limited to four numeric values (W.X.Y.Z)
However the [version spec](https://spec.openapis.org/oas/latest.html#info-object) for OpenAPI is just a string, so it can support more advanced patterns like semver.

[original issue](https://github.com/microsoftgraph/msgraph-metadata/issues/275)

We need to update [the convert settings](https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L28) to do a couple of things:
- [x] add a SemVerVersion (string) property.
- [x] default it to 1.0.0
- [ ] replace the clone implementation to use that field instead.
- [x] update [the reader](https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiInfoGenerator.cs#L78) to use that field instead.
- [x] mark the version field as obsolete.
- [x] change the version field to simply be a getter and a setter that reads and write to the SemVerVersion field instead.

Once all of that is built and shipped, update the generation pipeline to put the correct versions, and [give a heads up to the community](https://github.com/APIs-guru/openapi-directory/issues/1053)

**Comment by irvinesunday** [comment]
@baywet what clone implementation are you referring to?

**Comment by baywet** [comment]
The one in convert settings
