### ISSUE TITLE
$count path segment should not be added if a count function is present

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#347]
This is a bit of an edge case but between excel functions and raw count we're hitting conflicts for things that are semantically identical.

/workbookTables/$count
/workbookTables/microsoft.graph.count()

What I'm proposing is to not add/remove the raw count when a count function is defined.

**Comment by irvinesunday** [comment]
Help me understand the rationale for this fix?

**Comment by baywet** [comment]
Assuming #348 goes in we'll end up with:
/workbookTables/$count
/workbookTables/count()

Which once the special characters are stripped, we end up generating conflicting code paths.
I know it's an edge case, but even from a description/API aspect, having two different ways to count is going to be confusion to consumers.
If the API producers went through the trouble of defining a specific count function, they must be applying specific logic

**Comment by baywet** [comment]
the alternatives could be to remove the count function via xsl or to use an annotation to say that raw count is not supported on that collection (I don't know if such annotation exists)
