### ISSUE TITLE
Adds a setting to strip namespace prefix from path for OData methods

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#348]
right now we're projecting
/me/microsoft.graph.sendMail

with that setting, set to microsoft.graph we should be able to project instead

/me/sendMail

If a function/action is defined in a sub namespace like

/.../microsoft.graph.callRecords.activate

it should keep the subnamespace like so

/.../callRecords.activate

**Comment by irvinesunday** [comment]
Namespaces like `microsoft.graph.callRecords`, `microsoft.graph.security` and `microsoft.graph` are fully qualified namespaces. Why would we only want to use the last segments e.g. for the 1st two namespaces?

**Comment by andrueastman** [comment]
> Namespaces like `microsoft.graph.callRecords`, `microsoft.graph.security` and `microsoft.graph` are fully qualified namespaces. Why would we only want to use the last segments e.g. for the 1st two namespaces?
> 
> We currently use the setting `EnableUnqualifiedCall` to generate operation names without their namespaces.
> 
> https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L38

Does that mean changing the setting would change the paths currently generated from 

```
/me/microsoft.graph.sendMail
```
to 
```
/me/sendMail
```

**Comment by irvinesunday** [comment]
> > Namespaces like `microsoft.graph.callRecords`, `microsoft.graph.security` and `microsoft.graph` are fully qualified namespaces. Why would we only want to use the last segments e.g. for the 1st two namespaces?
> > We currently use the setting `EnableUnqualifiedCall` to generate operation names without their namespaces.
> > https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L38
> 
> Does that mean changing the setting would change the paths currently generated from
> 
> ```
> /me/microsoft.graph.sendMail
> ```
> 
> to
> 
> ```
> /me/sendMail
> ```

Correct

**Comment by irvinesunday** [comment]
We currently use the fully qualified namespace names in operations and type cast segments. Are we anticipating this setting to simplify the naming of both segments?

**Comment by baywet** [comment]
I didn't anticipate the impact on cast, in theory as long as the default namespace is defined it should be fine. But we might want to test a file of endpoints first.

Also do we have this default namespace information in the csdl?
https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_AddressingDerivedTypes

**Comment by irvinesunday** [comment]
> I didn't anticipate the impact on cast, in theory as long as the default namespace is defined it should be fine. But we might want to test a file of endpoints first.
> 
> Also do we have this default namespace information in the csdl? https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_AddressingDerivedTypes

Yes we do. Here's an example:

```XML
<NavigationProperty Name="registeredOwners" Type="Collection(graph.directoryObject)">
<Annotation Term="Org.OData.Validation.V1.DerivedTypeConstraint">
  <Collection>
    <String>microsoft.graph.appRoleAssignment</String>
    <String>microsoft.graph.endpoint</String>
    <String>microsoft.graph.servicePrincipal</String>
    <String>microsoft.graph.user</String>
  </Collection>
</Annotation>
```

**Comment by baywet** [comment]
To be specific, the derived type constraint is not what I was referring to but rather this:
> Services MAY additionally support the use of the unqualified name of a derived type in a URL by defining one or more default namespaces through the [Core.DefaultNamespace](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.md#DefaultNamespace) term defined in [[OData-VocCore]](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#VocCore). For more information on default namespaces, see Default Namespaces in [[OData-Protocol]](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#odata).

**Comment by irvinesunday** [comment]
We currently don't define this default namespace term in our CSDL.

**Comment by irvinesunday** [comment]
Do you think we need to enforce a requirement to have this default namespace (ex.: microsoft.graph) defined in the CSDL for us to use in stripping out the fully qualified names?

**Comment by baywet** [comment]
I think we need to separate two aspects:
- In the conversion process, if that term is defined, the conversion should not emit the default namespace as part of the prefix.
- We can only do that if the service defines it, otherwise the service the service won't understand requests from the client. (we shouldn't add it as part of the XSL)

As far as I can tell, it's not defined on the service side, however we know that AGS understands methods without the namespace prefix.

Few tests:

works
```
GET https://graph.microsoft.com/v1.0/groups/0f514b9e-8031-49e9-9ba2-2cf2e1d66ed4/members/microsoft.graph.user
```
works

```
GET https://graph.microsoft.com/v1.0/groups/0f514b9e-8031-49e9-9ba2-2cf2e1d66ed4/members/graph.user
```
(I believe this one works because there's a namespace alias from microsoft.graph to graph)

but this fails
```
https://graph.microsoft.com/v1.0/groups/0f514b9e-8031-49e9-9ba2-2cf2e1d66ed4/members/user
```

So here is my suggestion.

If EnableUnqualifiedCall is true, don't project namespace in cast segments and methods.

else if a Default Namespace is defined, don't emit that part when projecting type cast segments and methods.

Then (outside of the conditional blocks above) if a namespace strip for methods prefix is defined, strip that part from the beginning of the method namespace.

We could additionally add a namespace strip for type cast segments prefix that does the same for type case segments.


What do you think?

**Comment by baywet** [comment]
Additionally we could/should also project a smaller path segment if an alias is defined.

**Comment by irvinesunday** [comment]
If this is failing...
```
https://graph.microsoft.com/v1.0/groups/0f514b9e-8031-49e9-9ba2-2cf2e1d66ed4/members/user
```
won't that mean we'll end up generating failing endpoints if we stripped off the namespaces from operations?

You mention this _"else if a Default Namespace is defined, don't emit that part when projecting type cast segments and methods."_ 
Doesn't the spec say the opposite? 
>Services MAY additionally support the use of the unqualified name of a derived type in a URL by defining one or more default namespaces through the [Core.DefaultNamespace](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.md#DefaultNamespace) term defined in [[OData-VocCore]](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#VocCore).

Further, I don't think our dependent `OData.Edm` lib. currently supports the term `Core.DefaultNamespace`. I've tried in futile retrieving this value when defined in a sample CSDL.

_"namespace strip for methods"_ - are you referring to a convert setting that will hold this value?

**Comment by baywet** [comment]
```
https://graph.microsoft.com/v1.0/groups/0f514b9e-8031-49e9-9ba2-2cf2e1d66ed4/members/user
```
This will fail, I'm not suggesting we do this today. I've been reaching out to AGS folks to understand whether the default namespace is set on their end, but they replied that most likely not, waiting to get a confirmation.

> Further, I don't think our dependent OData.Edm lib. currently supports the term Core.DefaultNamespace. I've tried in futile retrieving this value when defined in a sample CSDL.

[The constants file doesn't have a trace for it](https://github.com/OData/odata.net/blob/4b1659c5af3cd410d4ac01f352175354c9bba4ba/src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyConstants.cs#L12) I think that kind of resolves our question here, since we don't have access to the information and we're time constrained, we probably don't have the luxury to wait for the OData team to turn around and add it.
[I've added an issue for them to add support for it](https://github.com/OData/odata.net/issues/2626)


Here is a recap of what I'm suggesting
1. add a `namespacePrefixToStripForMethodPaths` convert setting.
2. add a `namespacePrefixToStripForTypeCastPaths` convert setting.


(you can imagine the same chart with namespacePrefixToStripForTypeCastPaths when projecting type cast segments)

```mermaid
flowchart TD
     A[generate path segment] ---> B{EnableUnqualifiedCall?};
     B -- True --> C[use short name];
     B -- False --> E{Is namespace aliased?};
     E -- True --> F[project alias to segment];
     E -- False --> G[project namespace to segment];
     F ----> H[Add type name to segment];
     G ----> H[Add type name to segment];
     H ----> I{Is namespacePrefixToStripForMethodPaths empty?};
     I --  Yes --> D[Path segment generated];
     I -- No --> J[Strip prefix from generated segment];
     J ----> D[Path segment generated];
     C ----> D[Path segment generated];
```

**Comment by baywet** [comment]
(confirmed, AGS doesn't make use of the default namespace attribtute)

**Comment by irvinesunday** [comment]
Thank you for the visual representation 👌🏽

With regards to `namespacePrefixToStripForTypeCastPaths` does the service support referencing type casts be without their fully qualified names?
See: http://docs.oasis-open.org/odata/odata/v4.0/cs01/part2-url-conventions/odata-v4.0-cs01-part2-url-conventions.html#_Toc365046436
> A type cast using the `qualifiedEntityTypeName` to a type containing the property is required in order to expand a navigation property defined on a derived type.

**Comment by baywet** [comment]
Should the service be using the default namespace it would. Namespace aliasing also allows you to shorten it up. I don't think there's another way.
And we know that ags is using aliasing but it not using default namespace.
If you want I can introduce aliasing support in my diagram and remove the setting for type cast. This way we'd be feature complete to the exception of default namespace which needs to be added in edm anyway

**Comment by irvinesunday** [comment]
> Should the service be using the default namespace it would. Namespace aliasing also allows you to shorten it up. I don't think there's another way. And we know that ags is using aliasing but it not using default namespace. If you want I can introduce aliasing support in my diagram and remove the setting for type cast. This way we'd be feature complete to the exception of default namespace which needs to be added in edm anyway

This comment implies that we can't proceed to add the feature for striping type cast paths using the convert setting value?

**Comment by baywet** [comment]
If we made such a setting available, people using it would need to be aware of the risks it presents (crafting requests the service won't understand).
For type cast segments my suggestion at this point it simply to implement aliasing and no stripping, meaning that if a namespace or parent namespace is aliased, we simply project the aliased namespace instead of the full name. That should be safe since the service should understand the request. And as a failsafe we can always add a boolean setting (default true) "EnableUseOfAliasForTypeCastSegments" (or something along those lines).

What do you think?

**Comment by irvinesunday** [comment]
I agree. Maybe `bool` `AliasTypeCastSegments`. But I think the default should be `false`, which is the current behaviour.
However, is this currently blocking shipping of the dotnet SDK? If not, I would suggest moving it to a separate issue for now.

**Comment by baywet** [comment]
It's the same argument as for the methods. Yes we can ship SDKs as is. However we're highly likely to get feedback that having to put the fully qualified name as a code path to cast is "poor experience" at best, and fixing it post GA would mean a breaking change customers would need to handle code updated for.
This change should be simple enough to fast-track it with the other set of changes so we don't have to come back to it. Especially since the PRs for the other 2 issues are mostly done at this point.

Now, I understand it's getting late where you are and I'd suggest we take advantage of the time difference. Take some rest, and start with that tomorrow. Thoughts?

**Comment by baywet** [comment]
As an alternative @andrueastman or myself can pick it up tomorrow.

**Comment by irvinesunday** [comment]
> It's the same argument as for the methods. Yes we can ship SDKs as is. However we're highly likely to get feedback that having to put the fully qualified name as a code path to cast is "poor experience" at best, and fixing it post GA would mean a breaking change customers would need to handle code updated for. This change should be simple enough to fast-track it with the other set of changes so we don't have to come back to it. Especially since the PRs for the other 2 issues are mostly done at this point.
> 
> Now, I understand it's getting late where you are and I'd suggest we take advantage of the time difference. Take some rest, and start with that tomorrow. Thoughts?

Sounds good
