### ISSUE TITLE
Response object needs type property to identify collections

### ISSUE THREAD

**Issue by madansr7** [microsoft/OpenAPI.NET.OData#36]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

OpenAPI.NET.OData beta

### Steps to reproduce

When the return type is a collection the responses object should identify that as a`type:array` in the schema object. 
This is how it shows right now:

```json
"/workbooks/{driveItem-id}/workbook/worksheets": {
      "get": {
        "tags": [
          "workbooks.workbook.workbookWorksheet"
        ],
        "summary": "Get worksheets from workbooks",
        "operationId": "workbooks.workbook.ListWorksheets",
        "responses": {
          "200": {
            "description": "Retrieved navigation property",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/microsoft.graph.workbookWorksheet"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/error"
          }
        },
        "x-ms-docs-operation-type": "operation"
      }
```
The response from the path `"/workbooks/{driveItem-id}/workbook/worksheets"` is a collection and the payload looks like such:
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('e7e78c6b-edc1-4a64-967a-191762f770f9')/drive/items('01GP26K3AE24TDFMLPNBBISOVVWJ23VZMJ')/workbook/worksheets",
    "value": [
        {
            "@odata.id": "/users('e7e78c6b-edc1-4a64-967a-191762f770f9')/drive/items('01GP26K3AE24TDFMLPNBBISOVVWJ23VZMJ')/workbook/worksheets(%27%7B9AA98A93-6FFB-43F7-9FE3-6F64A5FB0D20%7D%27)",
            "id": "{9AA98A93-6FFB-43F7-9FE3-6F64A5FB0D20}",
            "name": "Sheet 1",
            "position": 0,
            "visibility": "Visible"
        },
        …
    ]
}
```
### Expected result

Responses object in the schema needs to include **"type": "array"**.

```json
"responses": {
              "200": {
                "description": "Retrieved navigation property",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "value": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/microsoft.graph.workbookWorksheet"
                          }
                        }
                      }
                    }
                  }
                }
```

**Comment by darrelmiller** [comment]
@madansr7  This issue is a blocker for us moving forward with our PowerShell SDK generation.  @xuzhg  Do you have time to work on this?

**Comment by xuzhg** [comment]
@darrelmiller  Did you check whether it is fixed in beta8 or not?

**Comment by darrelmiller** [comment]
I did not, sorry.  I didn't realize that release was available.  Let me try it.

**Comment by darrelmiller** [comment]
@xuzhg I'm still seeing the issue using the most recent libraries in the OData2OpenApi tool .

![image](https://user-images.githubusercontent.com/447694/62964857-d3c18380-bdd1-11e9-9439-7cc6c36a5201.png)

![image](https://user-images.githubusercontent.com/447694/62964887-e50a9000-bdd1-11e9-899a-b3519a7815b5.png)

**Comment by xuzhg** [comment]
@darrelmiller Would you help check "https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.0-beta9", Thanks.

**Comment by darrelmiller** [comment]
Will do.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darrelmiller** [comment]
Hey Sam,

That fixed it.

Thanks,

Darrel


________________________________

**Comment by xuzhg** [comment]
@darrelmiller Thanks for information.

@madansr7 It's fixed in "https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.0-beta9". Closed it. Thanls.

**Comment by madansr7** [comment]
@xuzhg , thanks for getting this out so quickly. 
@darrelmiller, please let me know if you come across any other issues.
