### ISSUE TITLE
Namespace stripping for functions/actions.

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#365]
Related to 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1691
RunningHuntingQuery is an action and only works with the full namespace or the entire namespace stripped. not `security.RunningHuntingQuery`
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1787
getDirectRoutingCalls is an action and only works with the full namespace or the entire namespace stripped. not `callRecords.getDirectRoutingCalls`

Stripping a specific prefix from namespace from Functions and Action can lead to invalid paths. 

Following the discussion in https://github.com/microsoft/OpenAPI.NET.OData/issues/348#issuecomment-1444244198

Does it make sense to only use aliasing for TypeSegments and strip the namespace for Functions/Actions? I'm not sure if there are cases where a function/action fails if the entire namespace is stripped off?

cc @baywet @irvinesunday

**Comment by baywet** [comment]
I provided [more context here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1787#issuecomment-1490421830) but I don't believe we should change any of the conversion logic at this point. OData semantics clearly indicate that the method should be able to be called with the fully qualified name, the aliased name and the short method name. AGS seems to be messing up the aliased scenario and we should open an ICM on them for that reason.
