### ISSUE TITLE
DELETE methods with no schema have 2XX response.

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#366]
Possibly a regression from to https://github.com/microsoft/OpenAPI.NET.OData/pull/357

The Delete methods generated with the latest version of the library now have the 2XX status range as opposes to the 204 code.

example
```yaml
    delete:
      tags:
        - communications.callRecord
      summary: Delete navigation property segments for communications
      operationId: communications.callRecords.sessions.DeleteSegments
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        2XX:
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
```

This results in Kiota generating return types for these methods for delete requests which may be misleading from a consumer point of view.

**Comment by irvinesunday** [comment]
Should the response type for `Delete` revert to `204` even when `UseSuccessStatusCodeRange` == `true`?

**Comment by andrueastman** [comment]
Yes. I don't think we want to give the information that something could be returned when it won't as this hasn't been the case for DELETE.
