### ISSUE TITLE
[Fix] Add support for other `Org.OData.Core.V1.RevisionKind` enum values

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#372]
OData has 3 supported [Revision Kinds](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.md#revisionkind):
- Added
- Modified
- Deprecated

Currently, version `1.4.0-preview2` only supports the annotation `Org.OData.Core.V1.RevisionKind/Deprecated`. 

A CSDL with the below annotation which includes the `Added` `RevisionKind` annotation currently throws a `System.InvalidOperationException` exception: "_The kind of the revision must be Deprecated._"

```XML
<Annotations Target="microsoft.graph.endWorkingTime(microsoft.graph.workingTimeSchedule)">
  <Annotation Term="Org.OData.Core.V1.Description" String="Triggers the policies associated with the end of working hours." ags:OwnerService="Microsoft.Teams.WorkingTime" />
  <Annotation Term="Org.OData.Core.V1.Revisions" ags:OwnerService="Microsoft.Teams.WorkingTime">
    <Collection>
      <Record>
        <PropertyValue Property="Date" Date="2023-04-05" />
        <PropertyValue Property="Kind">
          <EnumMember>Org.OData.Core.V1.RevisionKind/Added</EnumMember>
        </PropertyValue>
        <PropertyValue Property="RemovalDate" Date="2023-10-04" />
        <PropertyValue Property="Version" String="2023-04/PrivatePreview:TeamsWorkingTime" />
      </Record>
    </Collection>
  </Annotation>
</Annotations>
```

We need to modify the lib. to support the other revision kinds.

**Comment by darrelmiller** [comment]
I'm pretty sure that this is just a case of the team not knowing how they are supposed to add that annotation.

**Comment by irvinesunday** [comment]
Currently this is how the `Deprecated` revision kind is been added:
```XML
<Record>
  <PropertyValue Property="Date" Date="2023-03-02" />
  <PropertyValue Property="Description" String="Private preview for EPM AUthorization Systems APIs" />
  <PropertyValue Property="Kind">
    <EnumMember>Org.OData.Core.V1.RevisionKind/Deprecated</EnumMember>
  </PropertyValue>
  <PropertyValue Property="RemovalDate" Date="2023-05-30" />
  <PropertyValue Property="Version" String="2023-03/PrivatePreview:epmauthorizationsystems" />
</Record>
```

The `Added` revision kind would also be added in a similar way...
```XML
<Record>
  <PropertyValue Property="Date" Date="2023-04-05" />
  <PropertyValue Property="Kind">
    <EnumMember>Org.OData.Core.V1.RevisionKind/Added</EnumMember>
  </PropertyValue>
  <PropertyValue Property="RemovalDate" Date="2023-10-04" />
  <PropertyValue Property="Version" String="2023-04/PrivatePreview:TeamsWorkingTime" />
</Record>
```
What we currently have in the conversion lib at the moment, is a way of only reading the `Deprecated` revision kind annotations. So, when retrieving this revision kind for a given element, and the first one that is found is not of kind `Deprecated`, the library throws an exception, as expressed [here](https://github.com/microsoft/OpenAPI.NET.OData/blob/f9e45d0cb93a22b39a86f17379e6510e3bc0ce67/src/Microsoft.OpenApi.OData.Reader/Vocabulary/Core/DeprecatedRevisionsType.cs#L29-L32)
