### ISSUE TITLE
Update pipeline tasks

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#394]
See [this run for example](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=117453&view=results)

The following tasks need to be updated in the ADO pipeline:
- Credscan
- Policheck
- Binskim
- Publish security analysis (might be injected automatically by other tasks)
- Post analysis (same)

We've performed similar upgrades on Kiota, OpenAPI.net, etc... so you can have a look at existing PRs to check for the upgrade path.

[More information](https://aka.ms/gdn-v1-deprecation)

**Comment by irvinesunday** [comment]
Resolved by https://github.com/microsoft/OpenAPI.NET.OData/pull/362
