### ISSUE TITLE
/range/lastCell is missing in OpenAPI description

### ISSUE THREAD

**Issue by isvargasmsft** [microsoft/OpenAPI.NET.OData#402]
Path:
`/me/drive/items/{id}/workbook/names/{name}/range/lastCell` is missing in OpenAPI description.

Raptor error:
Original HTTP Snippet:
GET /v1.0/me/drive/items/{id}/workbook/names/{name}/range/lastCell HTTP/1.1
Host: graph.microsoft.com

Exception while processing /home/vsts/work/1/a/Snippets/range-lastcell-v1-httpSnippet.
Path segment 'lastCell' not found in path.

More of these reported here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1873

Originally reported: https://github.com/microsoftgraph/msgraph-metadata/issues/385

**Comment by baywet** [comment]
just as a precision here, we only expand functions on canonical paths to avoid over expansion.
So once fixed, the conversion will only expand on `/drives/{id}/items/{id}/workbook/names/{name}/range/lastCell`
