### ISSUE TITLE
Add the ability to change the request or response body content type based on an annotation

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#405]
[OneNote](https://learn.microsoft.com/en-us/graph/onenote-create-page#example-request) leverages multipart/form to create/update one note pages so the page, attachments and more can be pushed in a single call.

Currently the resulting OpenAPI description contains a basic JSON input/output for that endpoint which is incorrect.

We should:
1. identify a [capability annotation](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md) that could carry the information in the metadata
2. if none exist, define a new one
3. implement parsing it
4. implement the change in projection based on the metadata
5. add transforms in the metadata repo

**Comment by baywet** [comment]
Here is what the result should look like (for the request body) in the case of OneNote

```yaml
openapi: 3.0.1
info:
  title: Example
  description: Example
  version: 1.0.1
servers:
  - url: https://example.org
paths:
  /directoryObject:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                address:
                  $ref: '#/components/schemas/address'
                profileImage:
                  type: string
                  format: binary
            encoding:
              id:
                contentType: text/plain
              address:
                contentType: application/json
              profileImage:
                contentType: image/png
        responses:
          '204':
            content:
              application/json:
                schema:
                  type: string
components:
  schemas:
    address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
```

**Comment by baywet** [comment]
Thanks for the additional information.
How do you differentiate between the request and the response media type using that annotation? What if the media type is specific to an operation?

**Comment by darrelmiller** [comment]
I was going to suggest:
- SupportedRequestTypes
- AcceptableResponseTypes

but I think I like @baywet's suggestions better.

Have @garethj-msft and @MaximRouiller seen this proposal?

**Comment by MaximRouiller** [comment]
We haven't. Reading this now. Give me some time to ingest the information.

**Comment by MaximRouiller** [comment]
Alright, I have a few questions. 

* Are we trying to specify the exact MIME of the `Edm.Stream`? 
* I don't think setting the acceptable MIME type on the collection of pages make sense since the content of individual pages/resources of a oneNote payload could technically be different MIME types. I would see that definition belonging closer to the `<Property Name="content" Type="Edm.Stream" />` property. 

I might be completely off but I'm happy to jump on a call to clarify my viewpoint.

**Comment by irvinesunday** [comment]
> Alright, I have a few questions.
> 
> * Are we trying to specify the exact MIME of the `Edm.Stream`?
> * I don't think setting the acceptable MIME type on the collection of pages make sense since the content of individual pages/resources of a oneNote payload could technically be different MIME types. I would see that definition belonging closer to the `<Property Name="content" Type="Edm.Stream" />` property.
> 
> I might be completely off but I'm happy to jump on a call to clarify my viewpoint.

@MaximRouiller 
We already have the annotation `Org.OData.Core.V1.AcceptableMediaTypes` that applies to `Edm.Stream` types:

![image](https://github.com/microsoft/OpenAPI.NET.OData/assets/40403681/444a58fa-33f3-4fb6-8e87-38b4662b86ff)
[doc source](https://github.com/oasis-tcs/odata-vocabularies/blob/9c9a0957d0a83315a677c56d98d39d1bbd30e157/vocabularies/Org.OData.Core.V1.xml#L397)

And we already use it in our metadata, example:

![image](https://github.com/microsoft/OpenAPI.NET.OData/assets/40403681/e9964062-b425-4ad7-83f6-b27dce31dd6c)

However, this annotation doesn't specify the operations in which the MIME types are applicable, and hence they will be applied to all the operations in the generated path.

The problem we have at hand is specifying specific MIME types for specific operations, in cases where they could be different for the different operations.

To answer your questions:
1. Yes, we are trying to specify the range of acceptable MIME types for a property that is not necessarily of type `Edm.Stream`.
2. Changing the type will break the navigation property, `pages`
![image](https://github.com/microsoft/OpenAPI.NET.OData/assets/40403681/f22082e0-7145-4b4a-b448-d7021e5ee094)
