### ISSUE TITLE
How can I use in my REST API project for documentation ?

### ISSUE THREAD

**Issue by kuldip1490** [microsoft/OpenAPI.NET.OData#41]

**Comment by darrelmiller** [comment]
What exactly are you trying to do?

**Comment by kuldip1490** [comment]
@darrelmiller  Currently, I am using swagger for OData v4 .So How can I applied OpenAPI to my existing project?

**Comment by kuldip1490** [comment]
here is my sample code link : https://drive.google.com/file/d/1mGF269LS_-Tc1KpVqmKtOF3hz9jaCnId/view?usp=sharing
Please help me
