### ISSUE TITLE
Duplicate Path Parameters should be prevented

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#42]
In the Graph OpenAPI we get paths like this:

    '/me/calendar/calendarView/{event-id}/instances/{event-id}':

This causes problem when doing code-gen.  We should find a way to name the parameters so they are unique.

/cc @madansr7 @xuzhg

**Comment by madansr7** [comment]
the keys are generated based on the segment type. So, in this case both calendarView and instances are of type event. We can either change it such that when the second (duplicate) key segment is generated it will take after the segment name or change it universally so all key segments will take their name from the prior segment. 
I am leaning towards option #2.

**Comment by darrelmiller** [comment]
Just using the segment name is not going to be clear what needs to be passed.  In the above case, it would end up be `calendarView-Id` and `instances-id` which is not very helpful.

I think we should prefix the event-id with the previous segment if there is a duplicate.  Therefore we would have `event-id` and `instances-event-id`

We have the same issue with `https://graph.microsoft.com/v1.0/workbooks/{driveItemId}/children/{driveItemId}`

So this would give us `driveItem-id` and `children-driveItem-id`

**Comment by madansr7** [comment]
We can work to change the way you propose but that would create extremely long parameter names in a few cases. Here are a few examples where it starts to get crazy. But the benefits out weigh the negatives, so i am fine to move forward with this approach. 

`enrollmentTroubleshootingEvent` 
`macOSGeneralDeviceConfiguration` 
`deviceConfigurationUserOverview` 
`deviceConfigurationDeviceStatus` 
`telecomExpenseManagementPartner` 
`directoryObjectPartnerReference` 
`windows10MobileCompliancePolicy` 
`inferenceClassificationOverride` 
`targetedManagedAppConfiguration` 
`macOSDeviceFeaturesConfiguration` 
`plannerBucketTaskBoardTaskFormat` 
`deviceCompliancePolicyAssignment` 
`applePushNotificationCertificate` 
`multiValueLegacyExtendedProperty` 
`deviceConfigurationDeviceOverview` 
`singleValueLegacyExtendedProperty` 
`windowsPhone81CustomConfiguration` 
`windows10TeamGeneralConfiguration` 
`deviceManagementExchangeConnector` 
`managedAppPolicyDeploymentSummary` 
`enrollmentConfigurationAssignment` 
`androidGeneralDeviceConfiguration` 
`targetedManagedAppPolicyAssignment` 
`deviceEnrollmentLimitConfiguration` 
`termsAndConditionsAcceptanceStatus` 
`androidWorkProfileCompliancePolicy` 
`windowsInformationProtectionPolicy` 
`plannerProgressTaskBoardTaskFormat` 
`windowsPhone81GeneralConfiguration` 
`onPremisesConditionalAccessSettings` 
`managedDeviceMobileAppConfiguration` 
`appleDeviceFeaturesConfigurationBase` 
`deviceAndAppManagementRoleAssignment` 
`deviceAndAppManagementRoleDefinition` 
`plannerAssignedToTaskBoardTaskFormat` 
`deviceManagementTroubleshootingEvent` 
`windowsUpdateForBusinessConfiguration` 
`deviceConfigurationDeviceStateSummary` 
`mdmWindowsInformationProtectionPolicy` 
`androidWorkProfileCustomConfiguration` 
`windows10SecureAssessmentConfiguration` 
`deviceComplianceScheduledActionForRule` 
`windows10EndpointProtectionConfiguration` 
`deviceCompliancePolicyDeviceStateSummary` 
`deviceCompliancePolicySettingStateSummary` 
`windowsInformationProtectionAppLockerFile` 
`androidWorkProfileGeneralDeviceConfiguration` 
`managedDeviceMobileAppConfigurationAssignment` 
`managedDeviceMobileAppConfigurationUserStatus` 
`windowsInformationProtectionAppLearningSummary` 
`managedDeviceMobileAppConfigurationUserSummary` 
`managedDeviceMobileAppConfigurationDeviceStatus` 
`managedDeviceMobileAppConfigurationDeviceSummary` 
`deviceEnrollmentPlatformRestrictionsConfiguration` 
`windowsInformationProtectionNetworkLearningSummary` 
`windows10EnterpriseModernAppManagementConfiguration` 
`deviceEnrollmentWindowsHelloForBusinessConfiguration` 
`windowsDefenderAdvancedThreatProtectionConfiguration`

**Comment by darrelmiller** [comment]
Are these based on actual cases where there are duplicate parameter names?

**Comment by xuzhg** [comment]
@darrelmiller What should we do for this case 

`/groups/{group-id}/events/{event-id}/calendar/events/{event-id}/accept`

**Comment by xuzhg** [comment]
@darrelmiller @madansr7 

can we suffix number after the duplicated key:

```json
"/groups/{group-id}/events/{**event-id1**}/calendar/calendarView/_{event-id2_}/cancel": {
      "post": {
        "tags": [
          "groups.Actions"
        ],
        "summary": "Invoke action cancel",
        "operationId": "groups.events.calendar.calendarView.cancel",
        "parameters": [
          {
            "name": "group-id",
            "in": "path",
            "description": "key: group-id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-ms-docs-key-type": "group"
          },
          {
            "name": "**event-id1**",
            "in": "path",
            "description": "key: event-id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-ms-docs-key-type": "event"
          },
          {
            "name": "_event-id2_",
            "in": "path",
            "description": "key: event-id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-ms-docs-key-type": "event"
          }
        ],
```

**Comment by darrelmiller** [comment]
@xuzhg I'm fine with the number suffix.

**Comment by xuzhg** [comment]
fixed with suffix index. Thanks.
