### ISSUE TITLE
Stable Version 1.0.0 requires Microsoft.OData.Edm  7.6.1-beta

### ISSUE THREAD

**Issue by Rotbarsch** [microsoft/OpenAPI.NET.OData#43]
Installing the new stable 1.0.0 throws the following error:

Assembly 'Microsoft.OpenApi.OData.Reader' with identity 'Microsoft.OpenApi.OData.Reader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.OData.Edm, Version=7.6.1.30918, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.OData.Edm' with identity 'Microsoft.OData.Edm, Version=7.6.0.30605, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### Assemblies affected

Microsoft.OpenApi.OData.Reader

### Steps to reproduce

1) Install stable 1.0.0
2) be disappointed

### Expected result

A "stable" release shouldn't have dependencies to preview packages.

### Actual result

"Stable" release has dependencies to preview packages.

**Comment by darrelmiller** [comment]
I ran into this same issue.

**Comment by xuzhg** [comment]
@Rotanms @darrelmiller  Thanks for reporting this. OData.Edm 7.6.1 will release today. Once it's done, I will update the dependency to the latest one. Thanks.

**Comment by madansr7** [comment]
@Rotbarsch , thanks for your patience.

**Comment by djkunkel** [comment]
Is there a workaround for this? Is it possible to use this package at this time?

**Comment by darrelmiller** [comment]
I used the beta package and it worked fine for me.

**Comment by xuzhg** [comment]
@Rotbarsch @djkunkel @darrelmiller Thanks for reporting this. I just uploaded the 1.0.1 version targeting the ODL 7.6.1 RTM. Thanks.
