### ISSUE TITLE
Update period to dash for action names with MD5 

### ISSUE THREAD

**Issue by madansr7** [microsoft/OpenAPI.NET.OData#44]
Need to update overload function ids which have MD5 hash appended to them. Change the "." before the hash to "-" and then append the hash.

**Comment by madansr7** [comment]
@darrelmiller, can you confirm if this quick fix unblocks your scenarios?

**Comment by darrelmiller** [comment]
Will do.

**Comment by darrelmiller** [comment]
@madansr7 @xuzhg   That helps a whole lot.  It's not ideal, but definitely better.   What would be much better is if we only included the MD5 if there was a duplicate.  I realize that is likely much harder to do.

![image](https://user-images.githubusercontent.com/447694/66003091-2a167e80-e473-11e9-9ec5-4f0089a012a8.png)

**Comment by madansr7** [comment]
AFAIK, that's how it works today. MD5 is used only for the overloads. 
@xuzhg , can you please confirm.

**Comment by darrelmiller** [comment]
From the screenshot above it appears that there is only one function called `Get-ReportEmailActivityCount`.  However, there are two functions called `Get-ReportEmailActivityUserDetail`.  I suspect that all functions with parameters are getting the MD5 hash.

**Comment by xuzhg** [comment]
Fixed and merged at https://github.com/microsoft/OpenAPI.NET.OData/commit/6377ee0d470b0c6de78222f3a90ea3a36414b541
