### ISSUE TITLE
Support for Reference delete scenario on collection valued nav property with index in query parameter.

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#453]
Original issue at https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/471

Taking a look at the documentation at https://docs.microsoft.com/en-us/graph/api/group-delete-acceptedsenders?view=graph-rest-1.0&tabs=csharp, the conversion library is missing the path 

```http
DELETE /groups/{id}/acceptedSenders/$ref?$id=https://graph.microsoft.com/v1.0/users/{user-id}
```

Given the work in https://github.com/microsoft/OpenAPI.NET.OData/pull/112, DELETE operations were added to $ref paths that are `IndexableByKey`. We would need to investigate further the scenario where the DELETE operation can be added to the collection values navigation property with a mandatory query parameter for the index

**Comment by andrueastman** [comment]
Additional reference at https://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingReferencesbetweenEntities

>Resource paths addressing a single related entity reference can be used in DELETE requests to unrelate two entities. In OData 4.01, this includes resource paths that identify an individual entity reference within a related collection by key. In OData 4.0, resource paths addressing a collection of references MUST be followed by the system query option $id in order to identify a single entity reference within the collection to be removed. The entity-id specified by $id may be expressed absolute or relative to the request URL. For details see [[OData-Protocol]](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#odata).

Example 29: three ways of unrelating Categories(1) and Products(0); the second option is supported only in OData 4.01

```http
DELETE http://host/service/Categories(1)/Products/$ref?$id=../../Products(0)
DELETE http://host/service/Categories(1)/Products(0)/$ref
DELETE http://host/service/Products(0)/Category/$ref
```

**Comment by irvinesunday** [comment]
Below is an example of the desired output:

![image](https://github.com/microsoft/OpenAPI.NET.OData/assets/40403681/869bf575-52ae-4710-8eeb-16957ee044ab)

**Comment by andrueastman** [comment]
Thanks @irvinesunday . This looks like what we need really.
