### ISSUE TITLE
Edm model with hierarchical class where methods are defined in parent class

### ISSUE THREAD

**Issue by SenyaMur** [microsoft/OpenAPI.NET.OData#46]
No create methods for inherited class where in parent defined operations;

### Assemblies affected
OpenAPI.NET.OData  1.0.1

### Steps to reproduce

```cs
public class AccountModel : BaseEntityApiModel{
  public long Id {get; set;}
  public string Name {get; set;}
}

public class AccountModel : BaseEntityApiModel{
  public string AccountType {get; set;}
}
public class MyDbContext : DbContext {
  public DbSet<AccountModel> Accounts { get; set; }
}
public static IEdmModel GetEdmModel() {
      var builder = new ODataConventionModelBuilder();
      var baseEntity = builder.EntityType<BaseEntityApiModel>();
      baseEntity.Function("Attachments").ReturnsCollection<AttachmentApiModel>();
      
      builder.EntitySet<AccountModel>("Accounts");
      return builder.GetEdmModel();
}

public OpenApiDocument ConvertEdmToOpenApi(){
var model = SoftWell.Ctor.Api.Admin.AllConfigurations.GetEdmModel();
       OpenApiConvertSettings settings = new OpenApiConvertSettings {   
      EnableUnqualifiedCall = true,
      TopExample = 100
    };
var doc = model.ConvertToOpenApi(settings);
return doc;
}
```
### Expected result
In created OpenApiDocument method for **Attachments** created for Account 
 and BaseEntityApiModel entities. 

### Actual result
In created OpenApiDocument  no method for **Attachments** Account entity, only for BaseEntityApiModel.

**Comment by xuzhg** [comment]
@SenyaMur Thanks for trying the OpenAPI.OData library. 

From your description, "Attachments" is a function defined on base type, meanwhile entity set "Accounts" is an entity set defined on derived type.
In current OpenAPI.OData library, only consider the function defined on type of entity set. And use function on the derived type of such type. 

It seems that I should consider to apply the functions/actions defined on the based type of the entity set type. I'd like to welcome any contribution. If not, i will find time later to add such supporting.

**Comment by SenyaMur** [comment]
Thank's @xuzhg. I'll make the feature after holydays and create PR.
