### ISSUE TITLE
Duplicate operation Ids for paths with alternate keys

### ISSUE THREAD

**Issue by timayabi2020** [microsoft/OpenAPI.NET.OData#488]
The fix provided [here](https://github.com/microsoftgraph/msgraph-metadata/issues/305)only applies to regular paths and doesn't apply to actions and functions.
In the example screenshot below, it is expected that the operation Id for the alternate path should have something like ``communication.onlinemeeting_sendVirtualAppointmentReminderSmByOnlineMeetingId``

<img width="638" alt="image (2)" src="https://github.com/microsoft/OpenAPI.NET.OData/assets/10947120/ef123de6-4a02-4efb-94f0-d6bc9018edfe">

**Alternate path**

<img width="619" alt="image (3)" src="https://github.com/microsoft/OpenAPI.NET.OData/assets/10947120/acd5745a-3c6f-4a3d-97e7-4505485a2fe5">

**Comment by irvinesunday** [comment]
Closed by this PR: https://github.com/microsoft/OpenAPI.NET.OData/pull/489
