### ISSUE TITLE
Add support for retrieving multiple enum values from the `UpdateMethod` property of the `UpdateRestrictions` annotation

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#564]
We need to add support for retrieving multiple enum values from the `UpdateMethod` property value of `UpdateRestrictions` annotations. 

example:

```XML
<Annotations Target="microsoft.graph.customClaimsPolicy/claims">
  <Annotation Term="Org.OData.Capabilities.V1.UpdateRestrictions">
    <Record>
      <PropertyValue Property="UpdateMethod">
        <Collection>
          <EnumMember>Org.OData.Capabilities.V1.HttpMethod/PUT Org.OData.Capabilities.V1.HttpMethod/PATCH</EnumMember>
        </Collection>              
      </PropertyValue>
    </Record>
  </Annotation>
</Annotations>
```

**Comment by baywet** [comment]
Dumping some of the conversation elements:

We'll need to update these blocks (multiple places) not to be if/else, but if first condition, if second condition.
https://github.com/microsoft/OpenAPI.NET.OData/blob/46c149087f3fdcca62cca5a0590a26a4c673e2a9/src/Microsoft.OpenApi.OData.Reader/PathItem/EntityPathItemHandler.cs#L37

The enum above needs to be flaggable https://github.com/microsoft/OpenAPI.NET.OData/blob/46c149087f3fdcca62cca5a0590a26a4c673e2a9/src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/UpdateRestrictionsType.cs#L161
so it matches its vocab definition
https://github.com/oasis-tcs/odata-vocabularies/blob/a7850482cc83488d37c66c4e907f6a94406e1d05/vocabularies/Org.OData.Capabilities.V1.xml#L764C23-L764C33

And we might have to update the GetEnumMember helper so it supports flags enums.

https://github.com/microsoft/OpenAPI.NET.OData/blob/46c149087f3fdcca62cca5a0590a26a4c673e2a9/src/Microsoft.OpenApi.OData.Reader/Edm/RecordExpressionExtensions.cs#L96

**Comment by baywet** [comment]
Another aspect to consider when emitting the multiple operations is the operation id:
- they should not collide, including with POST when present
- PUT should be Update by default, New when POST is absent AND PATCH is present.
- PATCH should be Update
- POST should be New

This leaves a question of what should the Id be for PUT when all of POST/PATCH/PUT are present?
