### ISSUE TITLE
Support case-insensitive OData system query parameters

### ISSUE THREAD

**Issue by Ndiritu** [microsoft/OpenAPI.NET.OData#573]
OData 4.01 services support case-insensitive query parameters (without the `$` prefix) e.g. `filter`, `expand` etc - https://learn.microsoft.com/en-us/odata/concepts/queryoptions-overview#system-query-options

This should be reflected in the OpenAPI descriptions.

Here's an SDK [customer](https://github.com/microsoftgraph/msgraph-sdk-php/issues/1571) scenario impacted by this.

**Comment by andrueastman** [comment]
In my head this may actually be a service/workload issue.
`$filter` should be functionally equivalent to `filter` in odata 4.0 so using either shouldn't have different behavior. Specifying both in the openApi description would lead to larger openApi description and larger SDKs generated.

**Comment by Ndiritu** [comment]
Oh I see. Thanks @andrueastman. I skimmed through the docs a bit too fast.
Closing this.
