### ISSUE TITLE
OpenAPI exposes too many Parameters

### ISSUE THREAD

**Issue by LukasKathrein** [microsoft/OpenAPI.NET.OData#58]
Hi,

I have a simple REST Endpoint for querying Users:
```
[HttpGet]
[EnableQuery()]
public IQueryable<User> Get()
{
    var user = this._repository.GetAllUsers().AsQueryable();
    return user;
}
``` 

and my configuration for the ODATA Endpoint looks like this:

```
var builder = new ODataConventionModelBuilder(app.ApplicationServices);
builder.EntitySet<User>("User");
var model = builder.GetEdmModel();
app.UseMvc(routeBuilder => {
                routeBuilder.EnableDependencyInjection();
                routeBuilder.OrderBy().MaxTop(100).SkipToken();
                routeBuilder.MapODataServiceRoute("api", "api", model);
});
```

So I want to expose the orderBy, Top and skip parameters for my endpoints. However in the generated OpenAPI yaml I have also parameters for all other parameters e. g. search, filter, expand and so on. In e. g. the swagger-editor I can choose values for these parameters and send a request, which obviously will fail with a bad request, as the endpoint does not expose all parameters for ODATA.

Is there a way that the generated yaml files correspond to my exposed parameters. Or am i missing something here? My version of `Microsoft.OpenApi.OData` is 1.0.1 (stable release)

Any help is much appreciated. Thanks!

**Comment by xuzhg** [comment]
@LukasKathrein Thanks for reporting this. The short answer is "So far there's no way to generate yaml file based on server side configuration, if such configuration doesn't include in the client CSDL".

So, `routeBuilder.OrderBy().MaxTop(100).SkipToken();` is server side configuration, all such information is not returned to client if we query "~/$metadata".

**Comment by LukasKathrein** [comment]
Hi @xuzhg 
thank you for the quick reply, I was already suspecting something like this (still new to ODATA :) )
Best
Lukas
