### ISSUE TITLE
Delete operation missing for contained target navigation properties to collections of entities.

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#59]
For navigation properties we currently only seem to generate GET/PATCH/POST

```csharp
  // navigation property (Get/Patch/Post)
            _handlers[ODataPathKind.NavigationProperty] = new Dictionary<OperationType, IOperationHandler>
            {
                {OperationType.Get, new NavigationPropertyGetOperationHandler() },
                {OperationType.Patch, new NavigationPropertyPatchOperationHandler() },
                {OperationType.Post, new NavigationPropertyPostOperationHandler() }
            };
```
https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandlerProvider.cs#L63

I think we also need to implement delete for these.  And deleting contained entities is going to have a different URL than non-contained entities.  Can you confirm @xuzhg  ?

**Comment by xuzhg** [comment]
? I think so. 
See this line: 
https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs#L76

I try to recall the discussion:

1) For Containment navigation property

Contained Navigation Property  | Operation
--------|---------
Collection| Get, Post 
Single| Get, Patch

2) For non-Containment navigation property

Non-Contained Navigation Property  | Operation
--------|---------
Collection| Get
Single| Get

So, how about for the delete?

Contained Navigation Property  | Delete Operation?
--------|---------
Contained Collection|  delete❌  
non-Contained - Collection| delete ❌
Contained - Single| delete ✔️ 
non-Contained - Single| delete ✔️ 

I'd like to involve @Michael Pizzo for his input.

**Comment by darrelmiller** [comment]
@xuzhg yes, that looks like what we would want.  /cc @mikepizzo

**Comment by mikepizzo** [comment]
I agree that DELETE should be supported to a single-valued contained nav prop *provided that the property is non-nullable* (i.e., cardinality 0..1)

I'm not sure I'm reading Sam's last table correctly; I would expect DELETE to be supported against a contained collection-valued navigation property.

Are the values for Contained-Collection and non-Contained-Single in the table reversed?

**Comment by xuzhg** [comment]
Synced with Mike offline, we have the following `confirmed` table.


Contained:


Single-Valued | DELETE ~/entityset/{key}/contained-single-valued-Nav
-- | --
collection-valued | DELETE ~/entityset/{key}/contained-collection-valued-Nav/{navKey}

Non-contained:

Single-Valued | DELETE ~/entityset/{key}/single-valued-Nav/$ref
-- | --
collection-valued | DELETE ~/entityset/{key}/collection-valued-Nav/$ref?$id={navKey}

Nested navigation property:


Single-Valued | DELETE ~/entityset/{key}/contained-single-valued-Nav/single-valued-Nav/$ref   DELETE ~/entityset/{key}/contained-collection-valued-Nav/{navKey}/Single-Valued-Nav/$ref
-- | --
collection-valued | DELETE ~/entityset/{key}/contained-single-valued-Nav/{navKey}/collection-valued-Nav/$ref?$id={navKey}   DELETE ~/entityset/{key}/contained-collection-valued-Nav/{navKey}/collection-valued-Nav/$ref?$id={navKey}

**Comment by xuzhg** [comment]
@darrelmiller 
I added the delete support at: https://github.com/microsoft/OpenAPI.NET.OData/commit/a7ee00dbf4925aeaadfc92c9dd13102ba80d1b98

Would you please try it and verify whether the implementation meets your requirement?
