### ISSUE TITLE
Duplicate operation Ids between PATCH and PUT when both are supported

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#600]
follow up to #596 and #594

Happens in beta, but will eventually roll out to v1

```http
PUT /servicePrincipals/{servicePrincipal-id}/claimsPolicy
```
```http
PATCH /servicePrincipals/{servicePrincipal-id}/claimsPolicy
```

Both have the same `servicePrincipals.UpdateClaimsPolicy` operation id and they should not.

**Comment by irvinesunday** [comment]
PowerShell uses these two operation ids but distinguishes them by changing the `PUT` operation id from `servicePrincipals.UpdateClaimsPolicy` to `servicePrincipals_SetClaimsPolicy`. This happens via DevX API during slicing of OpenAPI for PowerShell. Barring the underscore, I wonder if we can rename all `UPDATE` operations to `xxx.Setyyy` ?

**Comment by baywet** [comment]
As far as I know, PowerShell is the only surface we have that depends on OperationIds. Copilots with Microsoft plugins manifest also use them, but when the manifest is generated from the description, the operation id gets copied and normalized. So any update should flow through.
Can you validate that changing the source won't break PowerShell downstream before proceeding to the change please?

**Comment by irvinesunday** [comment]
This won't affect PowerShell, because as I mentioned before, we ultimately transform `PUT` operationIds to use .SetXxx instead of .UpdateXxx via DevX API before consumption by AutoREST. 

@timayabi2020 to confirm that this assertion is true,  and that the proposed change will not affect PowerShell.

**Comment by baywet** [comment]
Great! Thanks everyone for triple checking before we make some changes. @irvinesunday good to proceed.
