### ISSUE TITLE
Add support for multiple namespaces in the CSDL.

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#63]
Currently Graph has multiple namespaces and the types do not get generated correctly.

**Comment by xuzhg** [comment]
@darrelmiller Would you share more details about the errors or problem? any example can help

**Comment by darrelmiller** [comment]
Hey Sam, sorry, the issue was a placeholder to remind me to come back and provide more details.  If you look at the beta API currently we have this:

![image](https://user-images.githubusercontent.com/447694/82500321-2a768f00-9ac1-11ea-804b-b0e696b7cf41.png)

There a bunch of types defined in microsoft.graph.callrecords.  I believe that if you try and convert this it fails during the processing. I will double check though as it may just return empty results for those operations.

**Comment by darrelmiller** [comment]
#ab4938

**Comment by ddyett** [comment]
AB#4938

**Comment by darrelmiller** [comment]
This already works.  We had an issue upstream in our pipeline.
