### ISSUE TITLE
Generated OpenAPI specification has some errors

### ISSUE THREAD

**Issue by unchase** [microsoft/OpenAPI.NET.OData#66]
OpenAPI specification generated by [Trippin sample service](https://services.odata.org/TripPinRESTierService/$metadata) OData specification with default `OpenApiConvertSettings` has some errors in [editor.swagger.io](https://editor.swagger.io).

### Assemblies affected

[Microsoft.OpenApi.OData v1.0.2](https://www.nuget.org/packages/Microsoft.OpenApi.OData)

### Steps to reproduce

1. Save OData specification from [Trippin sample service](https://services.odata.org/TripPinRESTierService/$metadata) to local xml-file (for example, **odata.xml**);
2. Use this code:
```csharp
public static void GenerateOpenApiDescription()
{
    IEdmModel model = GetEdmModel();
    OpenApiDocument document = model.ConvertToOpenApi();
    var outputJSON = document.SerializeAsJson(OpenApiSpecVersion.OpenApi3_0);
    System.IO.File.WriteAllText("openapi.json", outputJSON);
}

public static IEdmModel GetEdmModel()
{
    string csdlFilePath = @"odata.xml"; // saved before
    string csdl = System.IO.File.ReadAllText(csdlFilePath);
    IEdmModel model = CsdlReader.Parse(XElement.Parse(csdl).CreateReader());
    return model;
}
```
3. Paste OpenAPI json-specification from created **openapi.json** to [editor.swagger.io](https://editor.swagger.io).

### Expected result

Generated OpenAPI specification has not any errors.

### Actual result

Generated OpenAPI specification has some errors.

### Additional detail

![error](https://user-images.githubusercontent.com/29679226/83535082-46832300-a4fa-11ea-9b77-6cfec7d4e82d.png)

**Comment by xuzhg** [comment]
@unchase Thanks for reporting this.  It looks it's really issue that the key name is same as the one of the parameter name.
I am wondering how to fix it.

**Comment by xuzhg** [comment]
From the OpenApi specification, parameter name is case sensitive at https://swagger.io/specification/

![image](https://user-images.githubusercontent.com/9426627/83578526-dff70880-a4eb-11ea-9275-b4f6ff2d1ecc.png)

I checked with Darrel Miller that it seems it's a bug at Editor.
Of course, we need to double confirm and will reply to you later @unchase .
