### ISSUE TITLE
Update the nuget package description to include typical usage, for example settings

### ISSUE THREAD

**Issue by xuzhg** [microsoft/OpenAPI.NET.OData#70]
For example, update this line at: https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.Release.nuspec#L9

TO include the description about the usage.

**Comment by unchase** [comment]
@xuzhg You should add not only the description to the `.nuspec`, but also xml-comments in the library code, so that can see the description for the `OpenApiConvertSettings` (for each option like `EnableKeyAsSegment` and others) through intellisence for those who use the [Microsoft.OpenApi.OData](https://www.nuget.org/packages/Microsoft.OpenApi.OData) library.

**Comment by xuzhg** [comment]
@unchase

Thanks.
In the source code, I have the comments at https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L26. So, is it same as the your xml-comments ?

**Comment by unchase** [comment]
@xuzhg Yes, but you should include xml-file to nuget-package:

![xml](https://user-images.githubusercontent.com/29679226/83790569-132ec880-a6a1-11ea-82c2-394eb5ef9fb4.png)

Now i can't see description with intellisence:

![issue](https://user-images.githubusercontent.com/29679226/83790729-4f622900-a6a1-11ea-99e3-751333112bc7.png)

**Comment by xuzhg** [comment]
I see, thanks.

**Comment by xuzhg** [comment]
@unchase,

I had a fix for this at: https://github.com/microsoft/OpenAPI.NET.OData/commit/e0135613d60abb9e9b7a2862eabb233cae6fdfff

Would you please try this nightly, 
https://www.myget.org/feed/openapiodata/package/nuget/Microsoft.OpenApi.OData/1.0.2-Nightly202006041829

To connect to OpenAPI.OData.reader nightly feed, use this URL source https://www.myget.org/F/openapiodata/api/v3/index.json.

**Comment by unchase** [comment]
> @unchase,
> 
> I had a fix for this at: [e013561](https://github.com/microsoft/OpenAPI.NET.OData/commit/e0135613d60abb9e9b7a2862eabb233cae6fdfff)
> 
> Would you please try this nightly,
> https://www.myget.org/feed/openapiodata/package/nuget/Microsoft.OpenApi.OData/1.0.2-Nightly202006041829
> 
> To connect to OpenAPI.OData.reader nightly feed, use this URL source https://www.myget.org/F/openapiodata/api/v3/index.json.

@xuzhg All good:

![ok](https://user-images.githubusercontent.com/29679226/83811192-01a9e880-a6c2-11ea-879f-a4a6d5233518.png)

**Comment by xuzhg** [comment]
@unchase Cool. 
Close it as fixed.
