### ISSUE TITLE
Error in generating OpenAPI doc. when PrefixEntityTypeNameBeforeKey is set to true

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#75]
When [PrefixEntityTypeNameBeforeKey](https://github.com/microsoft/OpenAPI.NET.OData/blob/018cfb84fb08103e1144e0f7f3d5c083c624cd58/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L58) setting is set to `true`, attempting to generate an OpenAPI from CSDL throws an error. 
### Assemblies affected

`master` branch

### Steps to reproduce

1. Set this setting `PrefixEntityTypeNameBeforeKey = true`
2. Run the `OasGui` project. 
3. Browse for a CSDL file and load it for conversion.

### Expected result

The CSDL should successfully be converted to an OpenAPI spec. in the output window.

### Actual result

![Error-Specified-Key-Not-Found](https://user-images.githubusercontent.com/40403681/88163608-98534a00-cc1b-11ea-83cf-ec96c4211296.PNG)

### Additional detail

The error is thrown due to this [evaluation](https://github.com/microsoft/OpenAPI.NET.OData/blob/f08180c648741330b514149a9a61fba4ab420a24/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs#L144).

**Comment by xuzhg** [comment]
So, it seems when we query the dictionary, we should consider the setting ahead. If we have such setting, we use combine the key with the entity type as a new key, then use it to query the dict.

**Comment by irvinesunday** [comment]
> So, it seems when we query the dictionary, we should consider the setting ahead. If we have such setting, we use combine the key with the entity type as a new key, then use it to query the dict.

This [method ](https://github.com/microsoft/OpenAPI.NET.OData/blob/f08180c648741330b514149a9a61fba4ab420a24/src/Microsoft.OpenApi.OData.Reader/Edm/ODataKeySegment.cs#L83) might create multiple prefixed parameters like the example below, when the setting is enabled:

![Error-Specified-Key-Not-Found-MultipleParams](https://user-images.githubusercontent.com/40403681/88317806-7bee0500-cd22-11ea-95b7-447daffe50aa.PNG)

... and we might not be generating the right `keyName` with this https://github.com/microsoft/OpenAPI.NET.OData/blob/f08180c648741330b514149a9a61fba4ab420a24/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs#L136-L140
