### ISSUE TITLE
Non contained entity collections are generating paths to the entities

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#79]
Using Microsoft Graph v1.0 metadata the following paths are generated:

![image](https://user-images.githubusercontent.com/447694/90208721-73d03500-ddb7-11ea-896c-92ae290a97ca.png)

However many of these navigation properties are non-contained:

![image](https://user-images.githubusercontent.com/447694/90208773-99f5d500-ddb7-11ea-9516-cb1810e40639.png)

and therefore there should be no path to those entities.  All of the paths that have the {directoryobject-id} parameter should not be created.

**Comment by darrelmiller** [comment]
I think the issue is here:

https://github.com/microsoft/OpenAPI.NET.OData/blob/f08180c648741330b514149a9a61fba4ab420a24/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L220-L244

I think line 228 should have an `else`.  If the navigation property is not contained then we should not try and append a key to the path.

Thoughts? @xuzhg

**Comment by darrelmiller** [comment]
So, it turns out this isn't a bug, but it is a very useful convention.   In order to minimize the number of operations generated in the OpenAPI document it seems unnecessary to enable accessing items of a collection by key from a non-contained collection because the canonical URL will have its own operation.   

However, for non-contained collections it does seem useful to return a collection of $refs so that a consumer could identify all the canonical URLs of the referenced entities.

**Comment by baywet** [comment]
closing as this has already been addressed.
