### ISSUE TITLE
EdmOperations bound to derived types of navigation properties are missed from the generated document.

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/OpenAPI.NET.OData#83]
Let's say you have two entityTypes with an inheritance relationship   Vehicle <-- Car
Then you bind an operation to Car, e.g. DriveFast()

Then the only time Vehicle is used is as a nav property 
entitySet : vehicleTransporters(VehicleTransporter)

VehicleTransporter  --navProp-- vehicles(Vehicle)

None of the exisiting three cases in ODataPathProvider.cs will pick this operation up, as it is neither an entitySet  or Singleton, or a derived type of the types of those, of a non-derived navigation property.

A fourth case is needed for derived navigation properties.

We have quite a lot of actions bound to derived types in our model, so this is making our OAS file inaccurate.

**Comment by baywet** [comment]
@garethj-msft I believe this has been fixed via #88, can you confirm please?

**Comment by garethj-msft** [comment]
@baywet You're correct this was originally fixed by #88

**Comment by baywet** [comment]
thanks for confirming. closing.
