### ISSUE TITLE
Generate a root path that represents the service document.

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#85]
The root path should contain links to all top level entity sets and singletons in the entity container.

**Comment by baywet** [comment]
Hey @darrelmiller,
Do you mind expanding on the issue, what the current behavior is and what the expected one would be?
Also, would this have any sort of impact on Kiota?

**Comment by irvinesunday** [comment]
@darrelmiller @baywet don't we already have this feature? 
Enabled/disable by this setting: https://github.com/microsoft/OpenAPI.NET.OData/blob/2a7e87cadfd8bf887a9c8095a89253d70d81a6e4/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L171-L174
