### ISSUE TITLE
Edm..Date generates a sample value that is an ISO DateTime, not just Date and would fail its own validation.

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/OpenAPI.NET.OData#90]
When a property is of time Edm.Date, the wrong sample value is generated.

### Steps to reproduce

Add a property of type Edm.Date, generate OAS.

### Expected result

 <propertyName>:
      value:
        date: '0001-01-01'

### Actual result
<propertyName>:
      value:
        date: '0001-01-01**T00:00:00.0000000**'

**Comment by irvinesunday** [comment]
Transferred this issue to the `OpnAPI.NET` repo: https://github.com/microsoft/OpenAPI.NET/issues/1101
